### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by spirigweb** [tonioseiler/craft-commerce-wallee#5]
Hi
When making a payment, the total in the base currency is always used, not the converted order total. However, the correct currency is displayed. 

E.G. 
The order total in euros is
- 15,84 €

In CHF this would be
-14.89 CHF

15.84 CHF is displayed in the payment form.

In the order data, “paymentAmount” has the value 14.89 and “outstandingBalance” the value 15.84, which one is transmitted?

Are there any other parameters that need to be added to the payment form? 

<img width="570" alt="Bildschirmfoto 2024-09-24 um 15 10 00" src="https://github.com/user-attachments/assets/9ea50c8a-b729-4495-b35d-d5a1190b9b9c">

**Comment by spirigweb** [comment]
Update:
Its this value

`$lineItem->setAmountIncludingTax(round($order->getTotal(), 2));`

in CommerceWalleeService.php on line 

I think this should be converted to paymentCurrency.

**Comment by cmartinespinosa** [comment]
Hi @spirigweb ,

We have updated the plugin to address the conversion bug. May I confirm something? You have two or more payment currencies, correct? EUR and CHF? The bug was related to this.

This fix is compatible with both Craft 4 and Craft 5.

Please let us know if it works for you now, and we can close the issue.

Thanks for the feedback,

Carlos Martin
